<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \OaiPmhHarvester\Form\HarvestForm $form
 */

$plugins = $this->getHelperPluginManager();
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->headLink()
    ->appendStylesheet($assetUrl('css/oai-pmh-harvester.css', 'OaiPmhHarvester'));

$this->htmlElement('body')->appendAttribute('class', 'oai-pmh-harvester oai-pmh-harvester-index');
?>

<?= $this->pageTitle($translate('Harvester'), 1, $translate('OAI-PMH')) ?>

<div id="page-actions">
    <button form="harvest-repository" type="submit" class="button"><?= $translate('View sets') ?></button>
</div>

<h3><?= $translate('Set repository to harvest') ?></h3>

<?= $this->form($form) ?>
