<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \OaiPmhHarvester\Form\HarvestForm $form
 */

$translate = $this->plugin('translate');
?>

<?= $this->pageTitle($translate('Harvester'), 1, $translate('OAI-PMH')) ?>

<div id="page-actions">
    <button form="harvest-repository" type="submit" class="button"><?= $translate('View sets') ?></button>
</div>

<h3><?= $translate('Set repository to harvest') ?></h3>

<?= $this->form($form) ?>
