<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \OaiPmhHarvester\Form\SetsForm $form
 * @var string $endpoint
 * @var string $repositoryName
 * @var int|null $total
 * @var bool $harvestAllRecords
 */

$plugins = $this->getHelperPluginManager();
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->headLink()
    ->appendStylesheet($assetUrl('css/oai-pmh-harvester.css', 'OaiPmhHarvester'));

$this->htmlElement('body')->appendAttribute('class', 'oai-pmh-harvester oai-pmh-harvester-sets');

$sets = $form->getOption('sets') ?: [];
?>

<?= $this->pageTitle($translate('Prepare import'), 1, $translate('OAI-PMH Harvester')) ?>

<div id="page-actions">
    <button form="harvest-list-sets" type="submit" class="button"><?= $translate('Harvest') ?></button>
</div>

<h2><?= $repositoryName ?></h2>
<p>
    <?php if (is_null($total)): ?>
        <?= sprintf($translate('The repository %1$s (%2$s) has an undefined number of sets.'), $repositoryName, $endpoint) ?>
    <?php else: ?>
        <?= sprintf($translate('The repository %1$s (%2$s) has %3$d sets.'), $repositoryName, $endpoint, $total) ?>
        <?php if ($total && $total > count($sets)): ?>
            <?= sprintf($translate('Only the first %d are displayed.'), count($sets)) ?>
        <?php endif; ?>
    <?php endif; ?>
</p>

<?php if (!$harvestAllRecords): ?>
<p>
    <?= $translate('Please choose a set to import.') ?>
</p>
<?php endif; ?>

<?= $this->form($form) ?>
